### ISSUE TITLE
Move to debian `bullseye` base image for unified chromium packages

### ISSUE THREAD

**Issue by nucleardreamer** [balena-io-experimental/browser#138]
Currently `buster` as the base image has `chromium` and `chromium-common` packages split at different versions for different architectures. I think moving to buster (stable as of this issue) will make it so we can have the same packages for all architectures. This requires testing to make sure moving to `>v100` doesn't break this project.

See [here](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=chromium) for the list of chromium packages between the different debian releases.

**Comment by Iznogohul** [comment]
@nucleardreamer don’t know about testing but browser is now in bullseye(#148). 
Maybe mark this as closed?
