### ISSUE TITLE
Unable to pull Browser Image

### ISSUE THREAD

**Issue by deanMike** [balena-io-experimental/browser#140]
We're currently unable to create a build with the browser image. Seeing this: 
```Error response from daemon: error parsing HTTP 404 response body: invalid character 'S' looking for beginning of value: "Sorry, page not found."```

We've tried on multiple computers and Balena devices running in local mode.

**Comment by phil-d-wilson** [comment]
Hey there,

Sorry for the late reply. If you're still having the problem, can you put your docker-compose file here?
