### ISSUE TITLE
Auto restart browser

### ISSUE THREAD

**Issue by tnagels** [balena-io-experimental/browser#145]
Right now it is possible to close the browser using ALT+F4 or CTRL+w. It would be great to have server.js check if chromium is still running and trigger a restart when it closes.

**Comment by MiroYld** [comment]
Hello,
@tnagels do you tried to add 

```
restart: always
```
 in your docker-compose ?

**Comment by phil-d-wilson** [comment]
@MiroYld has the correct suggestion. I'll close this as solved.
