### ISSUE TITLE
Add feature to set headers in the request

### ISSUE THREAD

**Issue by oscni** [balena-io-experimental/browser#146]
Would be very useful to be able to set headers in the request.

**Comment by phil-d-wilson** [comment]
What headers in what request @oscni ?

**Comment by oscni** [comment]
http headers in http requests

**Comment by phil-d-wilson** [comment]
Sure. The block only makes requests itself to other services running on the device to automatically find what else it could display. Any actual requests are made through chrome-launcher which does not support request headers.

**Comment by oscni** [comment]
yeah i noticed that it doesn't support it natively but I actually got it working by modifying this repo. It involved spinning up a small local API webserver which present the header information and then a chrome pluing that loads that header information at startup and in all requests uses that header information. Just thought it would be good if the feature is supported in balena-browser since it's useful in many setups.
