### ISSUE TITLE
Disable password manager by default

### ISSUE THREAD

**Issue by jrr** [balena-io-experimental/browser#155]
The browser offered to save a password today:

![image](https://github.com/balena-labs-projects/browser/assets/164652/3de7e14d-686a-4183-aacf-3f3cee4702dc)

This should probably be off by default.

**Comment by phil-d-wilson** [comment]
@jrr I don't see a way to disable this programmatically. It appears that you have to do it per device in Chromium's settings, which is annoying. Sorry.
