### ISSUE TITLE
Feature request - autorefresh variable

### ISSUE THREAD

**Issue by vern3851** [balena-io-experimental/browser#156]
i’d love to have the page refresh every hour.
I can achieve this by hitting the API on the device like this:
curl -X POST http://192.168.1.111:5011/autorefresh/3600
However that does not survive a device reboot.
Is their a variable that could be used instead of the API?

**Comment by vern3851** [comment]
weve done some network hardening, hitting this API is possible from the console and pointing at loopback too.
eg curl -X POST http://127.0.0.1:5011/autorefresh/3600
but, still just a band-aid, would really like a proper variable to set.

**Comment by phil-d-wilson** [comment]
@vern3851 sorry it's so late but the feature is in version 2.9.0
