### ISSUE TITLE
Ability to disable long press context menu

### ISSUE THREAD

**Issue by mvheimburg** [balena-io-experimental/browser#170]
When running the browser as a kiosk with a touchscreen, the ability to disable long-press -> right-click would be a really nice feature.

**Comment by egidiusmengelberg** [comment]
yeah, having the same issue. No luck so far

**Comment by phil-d-wilson** [comment]
Unfortunately there is no setting in Chromium to disable the context menu and no other way the block can handle this. It is possible to handle a long press in javascript from the displaying page, but that obviously has to be down to individuals to implement.
